image: ubuntu:18.0.4

variables:
    # War filename
    WAR : openSilexTestAPI
    # RSYNC destination
    RSYNC_DEST : test
    # Remote IP
    REMOTE_IP : "138.102.159.37"
    # SCP Account
    SCP_ACCOUNT : mvidal
    # SCP key
    SCP_KEY : opensilex_key
    # RSYNC key
    RSYNC_KEY : opensilex_key
    # RSYNC user
    RSYNC_USER : phis
    # Manager Account
    MANAGER_ACCOUNT : phis
    # Manager Password (need to escape !)
    MANAGER_PASS : "fieldc1.61\!"
    # RSYNC Account
    RSYNC_ACCOUNT : phis
    SCRIPT_DIR : "$(dirname "$(readlink -f "$0")")"


# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "vendor"

build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
  artifacts:
    paths:
    - phis-webapp
    expire_in: 1 week

deploy:webapp:
  stage: deploy
  script:
     - git clone https://forgemia.inra.fr/OpenSILEX/opensilex-dev-tools.git ../scripts
  dependencies:
    - build:webapp