# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "vendor"
      
variables:
   SCP_ACCOUNT : "mvidal"
   REMOTE_IP : "138.102.159.37"
   KEY_DIR : "/tmp/id_rsa"
   TMP_DIR : "/tmp/phis-webapp"
   RSYNC_DEST : "test"
   RSYNC_USER : "phis"
   RSYNC_ACCOUNT : "phis"

build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
 

deploy:webapp:
  image: tetraweb/php:7.0
  stage: deploy
  before_script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$OPENSILEX_PRIVATE_KEY" | tr -d '\r' >> $KEY_DIR
    - chmod 400 $KEY_DIR
    - echo "${SSH_HOST_KEY}" > "~/.ssh/known_hosts"
    - apt-get install -y rsync
  script:
    - mkdir -p $TMP_DIR
    - cd $TMP_DIR
    - echo "ssh  -t $SCP_ACCOUNT@$REMOTE_IP"
    - echo "#### [Webapp] Rsync webapp files"
    - ssh -vvv   $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:phis /var/www/html/$RSYNC_DEST/"
    - rsync -arzv -e "ssh  -i $KEY_DIR" --progress --delete  --include='/web/documents/DatasetFiles/'  --include='/web/documents/SpectralHemisphericalReflectanceFiles/' --exclude='/web/documents/*' --exclude='.*' ./ $RSYNC_USER@$REMOTE_IP:/var/www/html/$RSYNC_DEST/
    - ssh  -vvv  -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:www-data /var/www/html/$RSYNC_DEST/"
    - ssh  -vvv  -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chmod -R ug+rw /var/www/html/$RSYNC_DEST/web"
    - echo "#### Create temporary directory"
    
    
    

 