# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "vendor"
      
variables:
   SCP_ACCOUNT : "mvidal"
   REMOTE_IP : "138.102.159.37"
   KEY_DIR : "/tmp/id_rsa"
   TMP_DIR : "/tmp/phis-webapp"
   RSYNC_DEST : "test"
   RSYNC_USER : "phis"
   RSYNC_ACCOUNT : "phis"

build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
 

deploy:webapp1:
  image: tetraweb/php:7.0
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$OPENSILEX_PRIVATE_KEY")
    - apt-get install rsync
  script:
    - echo "#### Create temporary directory"
    - mkdir -p $TMP_DIR
    - cd $TMP_DIR
    - echo "ssh  -t $SCP_ACCOUNT@$REMOTE_IP"
    - echo "#### [Webapp] Rsync webapp files"
    - ssh -vvv -t  $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:phis /var/www/html/$RSYNC_DEST/"
    - rsync -arzv -e "ssh" -progress --delete  --include='/web/documents/DatasetFiles/'  --include='/web/documents/SpectralHemisphericalReflectanceFiles/' --exclude='/web/documents/*' --exclude='.*' ./ $RSYNC_USER@$REMOTE_IP:/var/www/html/$RSYNC_DEST/
    - ssh  -vvv -t -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:www-data /var/www/html/$RSYNC_DEST/"
    - ssh  -vvv -t  -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chmod -R ug+rw /var/www/html/$RSYNC_DEST/web"
    
deploy:webapp2:
  image: tetraweb/php:7.0
  stage: deploy
  before_script:
    - echo $OPENSILEX_PRIVATE_KEY_PATH
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - echo "$SSH_HOST_KEY" >> "~/.ssh/known_hosts"
    - cp "$OPENSILEX_PRIVATE_KEY_PATH" ~/.ssh/
    - chmod -R 600 ~/.ssh
    - ls ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 600 $OPENSILEX_PRIVATE_KEY_PATH
    - apt-get install -y rsync
  script:
    - echo "#### Create temporary directory"
    - mkdir -p $TMP_DIR
    - cd $TMP_DIR
    - echo "ssh  -t -i $KEY_DIR $SCP_ACCOUNT@$REMOTE_IP"
    - echo "#### [Webapp] Rsync webapp files"
    - ssh -vvv  -t -i $OPENSILEX_PRIVATE_KEY_PATH  $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:phis /var/www/html/$RSYNC_DEST/"
    - rsync -arzv -e "ssh  -i $KEY_DIR" --progress --delete  --include='/web/documents/DatasetFiles/'  --include='/web/documents/SpectralHemisphericalReflectanceFiles/' --exclude='/web/documents/*' --exclude='.*' ./ $RSYNC_USER@$REMOTE_IP:/var/www/html/$RSYNC_DEST/
    - ssh  -vvv  -t -i $OPENSILEX_PRIVATE_KEY_PATH -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:www-data /var/www/html/$RSYNC_DEST/"
    - ssh  -vvv  -t -i $OPENSILEX_PRIVATE_KEY_PATH -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chmod -R ug+rw /var/www/html/$RSYNC_DEST/web"
        
    

 