# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "vendor"
      
variables:
   SCP_ACCOUNT : "mvidal"
   REMOTE_IP : "138.102.159.37"
   KEY_DIR : "${HOME}/.ssh/id_rsa"
   TMP_DIR : "/tmp/phis-webapp"
   RSYNC_DEST : "test"
   RSYNC_USER : "phis"
   RSYNC_ACCOUNT : "phis"

build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
 

deploy:webapp:
  image: tetraweb/php:7.0
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir "${HOME}/.ssh"
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ${HOME}/.ssh/config'
    - echo "$OPENSILEX_PRIVATE_KEY" | tr -d '\r' > ${HOME}/.ssh/id_rsa
    - chmod 400 $KEY_DIR
    - ssh-add <(echo "$OPENSILEX_PRIVATE_KEY")
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - apt-get install -y rsync
  script:
    - mkdir -p $TMP_DIR
    - cd $TMP_DIR
    - echo "ssh -i $KEY_DIR -t $SCP_ACCOUNT@$REMOTE_IP"
    - echo "#### [Webapp] Rsync webapp files"
    - ssh -vvv  -i $KEY_DIR $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:phis /var/www/html/$RSYNC_DEST/"
    - rsync -arzv -e "ssh  -i $KEY_DIR" --progress --delete  --include='/web/documents/DatasetFiles/'  --include='/web/documents/SpectralHemisphericalReflectanceFiles/' --exclude='/web/documents/*' --exclude='.*' ./ $RSYNC_USER@$REMOTE_IP:/var/www/html/$RSYNC_DEST/
    - ssh  -vvv  -i $KEY_DIR -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:www-data /var/www/html/$RSYNC_DEST/"
    - ssh  -vvv  -i $KEY_DIR -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chmod -R ug+rw /var/www/html/$RSYNC_DEST/web"
    - echo "#### Create temporary directory"
    
    
    

 