build_docs:
  stage: deploy
  script: 
    - curl --request POST \
      --form token=TOKEN \
      --form ref=master \
      --form "variables[INSTANCE]=test" \
      https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline