# define system environment variables 
variables:
  RSYNC_USER: phis
  SCP_ACCOUNT: mvidal

.cache_dependencies: &cache_dependencies
  cache:  
    key: "deploy-phis-webapp"
    paths:
      - "$CI_PROJECT_DIR/vendor" 

build:webapp:
  <<: *cache_dependencies
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 

.deploy: &deploy_template
  variables:
    REMOTE_IP: 138.102.159.37
    RSYNC_USER: phis
    SCP_ACCOUNT: mvidal
  image: tetraweb/php:7.0
  stage: deploy
  <<: *cache_dependencies
  before_script:
    - echo "Setting private key and known hosts"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ${HOME}/.ssh && touch ${HOME}/.ssh/known_hosts
    - ssh-keyscan -H "$REMOTE_IP" >> ${HOME}/.ssh/known_hosts
    - cp $SSH_PRIVATE_KEY_PATH  ${HOME}/.ssh/id_rsa
    - chmod 600 ${HOME}/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh -i ${HOME}/.ssh/id_rsa -tt $SCP_ACCOUNT@$REMOTE_IP "exit"
    - echo "successful connection"
    - apt-get install -y rsync
  script:
    - echo "#### [Webapp] Rsync webapp files"
    - ls $CI_PROJECT_DIR/vendor
    - ssh -i ${HOME}/.ssh/id_rsa  $SCP_ACCOUNT@$REMOTE_IP "sudo mkdir -p /var/www/html/$RSYNC_DEST/"
    - ssh -i ${HOME}/.ssh/id_rsa  $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:phis /var/www/html/$RSYNC_DEST/"
    - echo $RSYNC_USER@$REMOTE_IP:/var/www/html/$RSYNC_DEST/
    - rsync --quiet  -arzv -e  "ssh  -i ${HOME}/.ssh/id_rsa" --progress --delete  --include='/web/documents/DatasetFiles/'  --include='/web/documents/SpectralHemisphericalReflectanceFiles/' --exclude='/web/documents/*' --exclude='.*' ./ $RSYNC_USER@$REMOTE_IP:/var/www/html/$RSYNC_DEST/
    - ssh -i ${HOME}/.ssh/id_rsa -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:www-data /var/www/html/$RSYNC_DEST/"
    - ssh -i ${HOME}/.ssh/id_rsa -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chmod -R ug+rw /var/www/html/$RSYNC_DEST/web"

deploy:webapp:
  <<: *deploy_template
  variables:
    REMOTE_IP: 138.102.159.37
    RSYNC_DEST: test
  only:
    - master
        
deploy:webapp:modularity:
  <<: *deploy_template
  variables:
    REMOTE_IP: 138.102.159.37
    RSYNC_DEST: test-modularity
  only:
    - modularity

deploy:webapp:shinyproxy:
  <<: *deploy_template
  variables:
    REMOTE_IP: 138.102.159.37
    RSYNC_DEST: test-shinyproxy
  only:
    - shiny-proxy-test