# define system environment variables 
cache:
    key:
      files:
        - composer.lock
    paths:
      - "vendor"
      
variables:
   SCP_ACCOUNT : "mvidal"
   REMOTE_IP : "138.102.159.37"
   TMP_DIR : "/tmp/phis-webapp"
   RSYNC_DEST : "test"
   RSYNC_USER : "phis"
   RSYNC_ACCOUNT : "phis"

build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
 

deploy:webapp3:
  image: tetraweb/php:7.0
  stage: deploy
  when : manual
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p $HOME/.ssh && touch $HOME/.ssh/known_hosts
    - ssh-keyscan -H "$REMOTE_IP" >> $HOME/.ssh/known_hosts
    - echo "ssh host"
    - cat $HOME/.ssh/known_hosts
    - chmod 600 $HOME/.ssh/known_hosts
    - cp $OPENSILEX_PRIVATE_KEY_PATH  $HOME/.ssh/id_rsa
    - chmod 400  $HOME/.ssh/id_rsa
    - ls $HOME/.ssh
    - eval $(ssh-agent -s)
    - echo "private key"
    - cat $HOME/.ssh/id_rsa
    - echo 'ssh -vvv -i $HOME/.ssh/id_rsa -tt $SCP_ACCOUNT@$REMOTE_IP "exit"'
    - ssh -i $HOME/.ssh/id_rsa -tt $SCP_ACCOUNT@$REMOTE_IP "exit"
    - echo "successful connection"
    - apt-get install -y rsync
  script:
    - echo "#### Create temporary directory"
    - mkdir -p $TMP_DIR
    - cd $TMP_DIR
    - echo "#### [Webapp] Rsync webapp files"
    - ssh -i $HOME/.ssh/id_rsa  $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:phis /var/www/html/$RSYNC_DEST/"
    - rsync -arzv -e "ssh  -i $HOME/.ssh/id_rsa" --progress --delete  --include='/web/documents/DatasetFiles/'  --include='/web/documents/SpectralHemisphericalReflectanceFiles/' --exclude='/web/documents/*' --exclude='.*' ./ $RSYNC_USER@$REMOTE_IP:/var/www/html/$RSYNC_DEST/
    - ssh -i $HOME/.ssh/id_rsa -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:www-data /var/www/html/$RSYNC_DEST/"
    - ssh -i $HOME/.ssh/id_rsa -p22 $SCP_ACCOUNT@$REMOTE_IP "sudo chmod -R ug+rw /var/www/html/$RSYNC_DEST/web"
        
