# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "vendor"

build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
 

deploy:webapp:
  image: tetraweb/php:7.0
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$OPENSILEX_PRIVATE_KEY")
    - apt-get install -y rsync
  script:
    - git clone https://forgemia.inra.fr/OpenSILEX/opensilex-dev-tools.git ../scripts
 