# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "vendor"
      
variables:
   SCP_ACCOUNT : mvidal
   REMOTE_IP : "138.102.159.37"
   KEY_DIR : "/tmp/opensilex_key"


build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
 

deploy:webapp:
  image: tetraweb/php:7.0
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$OPENSILEX_PRIVATE_KEY")
    - apt-get install -y rsync
  script:
    - TMP_DIR = "$(mktemp -d)"
    - echo $OPENSILEX_PRIVATE_KEY >> $KEY_DIR
    - chmod 400 $KEY_DIR
    - chmod 400 $KEY_DIR
    - cd $TMP_DIR
    - echo "ssh -i $KEY_DIR -t $SCP_ACCOUNT@$REMOTE_IP"
    - echo "#### [Webapp] Rsync webapp files"
    - ssh -i $KEY_DIR -t $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:phis /var/www/html/$RSYNC_DEST/"
    - rsync -arzv -e "ssh -i $KEY_DIR" --progress --delete  --include='/web/documents/DatasetFiles/'  --include='/web/documents/SpectralHemisphericalReflectanceFiles/' --exclude='/web/documents/*' --exclude='.*' ./ $RSYNC_USER@$REMOTE_IP:/var/www/html/$RSYNC_DEST/
    - ssh -i $KEY_DIR -t $SCP_ACCOUNT@$REMOTE_IP "sudo chown -R phis:www-data /var/www/html/$RSYNC_DEST/"
    - ssh -i $KEY_DIR -t $SCP_ACCOUNT@$REMOTE_IP "sudo chmod -R ug+rw /var/www/html/$RSYNC_DEST/web"
    - echo "#### Create temporary directory"
    
    
    

 