image: ubuntu:18.0.4

# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "phis-webapp/vendor"

webappBuild:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
  artifacts:
    paths:
    - phis-webapp
    expire_in: 1 week
