# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "vendor"

build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
 

deploy:webapp:
  image: ubuntu:18.04
  stage: deploy
  script:
    - apt-get update && apt-get install \
        rsync \
        openssh-client \
        ca-certificates \
    - git clone https://forgemia.inra.fr/OpenSILEX/opensilex-dev-tools.git ../scripts
 