image: ubuntu:18.0.4

# define system environment variables 
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "vendor"

build:webapp:
  image: composer:1.9.1
  stage: build
  script:
     - composer install --ignore-platform-reqs 
 

deploy:webapp:
  stage: deploy
  script:
     - git clone https://forgemia.inra.fr/OpenSILEX/opensilex-dev-tools.git ../scripts
 