<?php

//******************************************************************************
//                                       YiiDataModel.php
// PHIS-SILEX
// Copyright © INRA 2019
// Creation date: 12 mars 2019
// Contact: morgane.vidal@inra.fr, anne.tireau@inra.fr, pascal.neveu@inra.fr
//******************************************************************************

namespace app\models\yiiModels;

use Yii;
use app\models\wsModels\WSActiveRecord;

/**
 * Model for the data. Used with web services
 * @author Morgane Vidal <morgane.vidal@inra.fr>
 */
class YiiDataModel extends WSActiveRecord {

    /**
     * Date of the data.
     * @var string expected format : YYYY-MM-DDTHH:MM:SSZ
     */
    public $date;

    /**
     * uri of the variable.
     * @example http://www.opensilex.org/demo/id/variables/v004
     * @var string
     */
    public $variable;

    /**
     * uri of the object concerned by the data.
     * @example http://www.opensilex.org/demo/2018/o18000076
     * @var string
     */
    public $object;

    /**
     * Uri of the provenance of the data.
     * @example http://www.opensilex.org/id/provenance/02465464
     * @var string
     */
    public $provenance;

   

    /**
     * 
     * @param string $pageSize number of elements per page
     * @param string $page current page 
     */
    public function __construct($pageSize = null, $page = null) {
        $this->wsModel = new \app\models\wsModels\WSDataModel();
        $this->pageSize = ($pageSize !== null || $pageSize === "") ? $pageSize : null;
        $this->page = ($page !== null || $page != "") ? $page : null;
    }

    /**
     * 
     * @return array the rules of the attributes
     */
    public function rules() {
        return [
            [['variable', 'object', 'provenance'], 'string'],
            [['variable', 'object', 'provenance'], 'safe'],
        ];
    }

    /**
     * 
     * @return array the labels of the attributes
     */
    public function attributeLabels() {
        return [
            'uriProvenance' => Yii::t('app', 'URI'),
            'variables' => Yii::t('app', 'Quantitative Variable'),
            'creationDate' => Yii::t('app', 'Dataset Creation Date'),
            'wasGeneratedBy' => Yii::t('app', 'Was Generated By'),
            'wasGeneratedByDescription' => Yii::t('app', 'Description'),
            'file' => Yii::t('app', 'Data') . " " . Yii::t('app', 'File'),
            'documentsUris' => Yii::t('app', 'Documents'),
            'variable' => Yii::t('app', 'Variable'),
            'object' => Yii::t('app', 'Object'),
            'provenance' => Yii::t('app', 'Provenance')
        ];
    }

    protected function arrayToAttributes($array) {
        throw new Exception('Not implemented');
    }

}
