<?php

return [
    'adminEmail' => 'admin@example.com',
    'baseURI' => 'http://www.phenome-fppn.fr/phis/',
    'platform' => 'Phis',
    'platformCode' => 'PHS',
    
    //ONTOLOGY -----------------------------------------------------------------
    //-------- Concepts
    'Lens' => 'http://www.phenome-fppn.fr/vocabulary/2017#Lens',
    'Plot' => 'http://www.phenome-fppn.fr/vocabulary/2017#Plot',
    'Species' => 'http://www.phenome-fppn.fr/vocabulary/2017#Species',
    'Variety' => 'http://www.phenome-fppn.fr/vocabulary/2017#Variety',
    'Experiment' => 'http://www.phenome-fppn.fr/vocabulary/2017#Experiment',
    'Project' => 'http://www.phenome-fppn.fr/vocabulary/2017#Project',
    'Camera' => 'http://www.phenome-fppn.fr/vocabulary/2017#Camera',
    'HemisphericalCamera' => 'http://www.phenome-fppn.fr/vocabulary/2017#HemisphericalCamera',
    'HyperspectralCamera' => 'http://www.phenome-fppn.fr/vocabulary/2017#HyperspectralCamera',
    'MultispectralCamera' => 'http://www.phenome-fppn.fr/vocabulary/2017#MultispectralCamera',
    'RGBCamera' => 'http://www.phenome-fppn.fr/vocabulary/2017#RGBCamera',
    'TIRCamera' => 'http://www.phenome-fppn.fr/vocabulary/2017#TIRCamera',
    'LiDAR' => 'http://www.phenome-fppn.fr/vocabulary/2017#LiDAR',
    'Spectrometer' => 'http://www.phenome-fppn.fr/vocabulary/2017#Spectrometer',
    'Installation' => 'http://www.phenome-fppn.fr/vocabulary/2017#Installation',
    'UAV' => 'http://www.phenome-fppn.fr/vocabulary/2017#UAV',
    'AcquisitionSessionUAVDocument' => 'http://www.phenome-fppn.fr/vocabulary/2017#AcquisitionSessionUAVDocument',
    'FieldRobot' => 'http://www.phenome-fppn.fr/vocabulary/2017#FieldRobot',
    'AcquisitionSessionPhenomobileDocument' => 'http://www.phenome-fppn.fr/vocabulary/2017#AcquisitionSessionPhenomobileDocument',
    
    'Infrastructure' => 'http://www.phenome-fppn.fr/vocabulary/2017#Infrastructure',
    'LocalInfrastructure' => 'http://www.phenome-fppn.fr/vocabulary/2017#LocalInfrastructure',
    'NationalInfrastructure' => 'http://www.phenome-fppn.fr/vocabulary/2017#NationalInfrastructure',
    'EuropeanInfrastructure' => 'http://www.phenome-fppn.fr/vocabulary/2017#EuropeanInfrastructure',
    'Installation' => 'http://www.phenome-fppn.fr/vocabulary/2017#Installation',
    
    //-------- Relations
    'aperture' => 'http://www.phenome-fppn.fr/vocabulary/2017#aperture',
    'attenuatorFilter' => 'http://www.phenome-fppn.fr/vocabulary/2017#attenuatorFilter',
    'dateOfLastCalibration' => 'http://www.phenome-fppn.fr/vocabulary/2017#dateOfLastCalibration',
    'dateOfPurchase' => 'http://www.phenome-fppn.fr/vocabulary/2017#dateOfPurchase',
    'focalLength' => 'http://www.phenome-fppn.fr/vocabulary/2017#focalLength',
    'fromSpecies' => 'http://www.phenome-fppn.fr/vocabulary/2017#fromSpecies',
    'fromVariety' => 'http://www.phenome-fppn.fr/vocabulary/2017#fromVariety',
    'halfFieldOfView' => 'http://www.phenome-fppn.fr/vocabulary/2017#halfFieldOfView',
    'hasAlias' => 'http://www.phenome-fppn.fr/vocabulary/2017#hasAlias',
    'hasBrand' => 'http://www.phenome-fppn.fr/vocabulary/2017#hasBrand',
    'hasExperimentModalities' => 'http://www.phenome-fppn.fr/vocabulary/2017#hasExperimentModalities',
    'isPartOf' => 'http://www.phenome-fppn.fr/vocabulary/2017#isPartOf',
    'Motivation' => 'http://www.w3.org/ns/oa#Motivation',
    'hasLens' => 'http://www.phenome-fppn.fr/vocabulary/2017#hasLens',
    'hasPart' => 'http://www.phenome-fppn.fr/vocabulary/2017#hasPart',
    'hasRepetition' => 'http://www.phenome-fppn.fr/vocabulary/2017#hasRepetition',
    'height' => 'http://www.phenome-fppn.fr/vocabulary/2017#height',
    'inServiceDate' => 'http://www.phenome-fppn.fr/vocabulary/2017#inServiceDate',
    'label' => 'rdfs:label',
    'maxWavelength' => 'http://www.phenome-fppn.fr/vocabulary/2017#maxWavelength',
    'measuredVariable' => 'http://www.phenome-fppn.fr/vocabulary/2017#measuredVariable',
    'minWavelength' => 'http://www.phenome-fppn.fr/vocabulary/2017#minWavelength',
    'pixelSize' => 'http://www.phenome-fppn.fr/vocabulary/2017#pixelSize',
    'rdfsLabel' => 'http://www.w3.org/2000/01/rdf-schema#label',
    'rdfType' => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
    'scanningAngularRange' => 'http://www.phenome-fppn.fr/vocabulary/2017#scanningAngularRange',
    'scanAngularResolution' => 'http://www.phenome-fppn.fr/vocabulary/2017#scanAngularResolution',
    'source' => 'http://purl.org/dc/terms/source',
    'spectralSamplingInterval' => 'http://www.phenome-fppn.fr/vocabulary/2017#spectralSamplingInterval',
    'spotHeight' => 'http://www.phenome-fppn.fr/vocabulary/2017#spotHeight',
    'spotWidth' => 'http://www.phenome-fppn.fr/vocabulary/2017#spotWidth',
    'type' => 'rdf:type',
    'waveband' => 'http://www.phenome-fppn.fr/vocabulary/2017#waveband',
    'wavelength' => 'http://www.phenome-fppn.fr/vocabulary/2017#wavelength',
    'width' => 'http://www.phenome-fppn.fr/vocabulary/2017#width',
    
];
